// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWvUxC8E7x3m6dYYA3OTY1sEYA8-WRfDU',
    appId: '1:548447367008:web:e1d26c45f12d1dd1d37805',
    messagingSenderId: '548447367008',
    projectId: 'convenz-customer-dfce7',
    authDomain: 'convenz-customer-dfce7.firebaseapp.com',
    storageBucket: 'convenz-customer-dfce7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz9k2odoBRaGTf_UB8H0M4W2xb4NP_8Tg',
    appId: '1:548447367008:android:3042c52b71ffd90cd37805',
    messagingSenderId: '548447367008',
    projectId: 'convenz-customer-dfce7',
    storageBucket: 'convenz-customer-dfce7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiSnellYfFovH8QYcPPxZs4wYQrMbl8rY',
    appId: '1:548447367008:ios:1b68441ff6c5a480d37805',
    messagingSenderId: '548447367008',
    projectId: 'convenz-customer-dfce7',
    storageBucket: 'convenz-customer-dfce7.firebasestorage.app',
    iosBundleId: 'com.example.convenzCustomerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiSnellYfFovH8QYcPPxZs4wYQrMbl8rY',
    appId: '1:548447367008:ios:1b68441ff6c5a480d37805',
    messagingSenderId: '548447367008',
    projectId: 'convenz-customer-dfce7',
    storageBucket: 'convenz-customer-dfce7.firebasestorage.app',
    iosBundleId: 'com.example.convenzCustomerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWvUxC8E7x3m6dYYA3OTY1sEYA8-WRfDU',
    appId: '1:548447367008:web:c37d1f73fe06af3dd37805',
    messagingSenderId: '548447367008',
    projectId: 'convenz-customer-dfce7',
    authDomain: 'convenz-customer-dfce7.firebaseapp.com',
    storageBucket: 'convenz-customer-dfce7.firebasestorage.app',
  );

}